development:
  clients:
    default:
      uri: mongodb://127.0.0.1:27017/inventory_api_development

test:
  clients:
    default:
      uri: mongodb://127.0.0.1:27017/inventory_api_test

production:
  clients:
    default:
      uri: <%= ENV["MONGODB_URI"] %>